ip_forward: true
network_compression_threshold: 256
stats: e09d4552-4a8b-4598-91c5-8b0edb00c6aa
groups:
  BinaryBeauty:
  - admin
  BinaryBench:
  - admin
  Hacks:
  - admin
  KiraBerry:
  - admin
  Byron:
  - admin
  fireflydestroyer:
  - admin
servers:
  hub:
    motd: '&1BinaryNetwork Hub - Forced Host'
    address: localhost:25564
    restricted: false
  game:
    motd: '&1BinaryNetwork Game - Forced Host'
    address: localhost:25563
    restricted: false
timeout: 30000
player_limit: -1
listeners:
- query_port: 25565
  motd: '&1BinaryNetwork'
  priorities:
  - hub
  - game
  bind_local_address: true
  tab_list: SERVER
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 1
  tab_size: 60
  ping_passthrough: false
  force_default_server: true
permissions:
  default:
  - bungeecord.command.server
  mod:
  - ab.warn.temp
  - ab.tempwarn.notify
  - ab.warn.perma
  - ab.warn.notify
  - ab.warn.undo
  - ab.mute.temp
  - ab.tempmute.notify
  - ab.mute.perma
  - ab.mute.notify
  - ab.mute.undo
  - ab.kick.use
  - ab.kick.notify
  - ab.ban.temp
  - ab.tempban.notify
  - ab.ban.perma
  - ab.ban.notify
  - ab.ban.ip
  - ab.ipban.notify
  - ab.ban.undo
  - ab.check
  - ab.banlist
  - ab.history
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.send
  - bans.superadmin
  - ab.warn.temp
  - ab.tempwarn.notify
  - ab.tempwarn.exempt
  - ab.warn.perma
  - ab.warn.notify
  - ab.warn.exempt
  - ab.warn.undo
  - ab.mute.temp
  - ab.tempmute.notify
  - ab.tempmute.exempt
  - ab.mute.perma
  - ab.mute.notify
  - ab.mute.exempt
  - ab.mute.undo
  - ab.kick.use
  - ab.kick.notify
  - ab.kick.exempt
  - ab.ban.temp
  - ab.tempban.notify
  - ab.tempban.exempt
  - ab.ban.perma
  - ab.ban.notify
  - ab.ban.exempt
  - ab.ban.ip
  - ab.ipban.notify
  - ab.ipban.exempt
  - ab.ban.undo
  - ab.check
  - ab.banlist
  - ab.history
  - ab.systemprefs
  - ab.reload
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
