ip_forward: true
network_compression_threshold: 256
stats: e09d4552-4a8b-4598-91c5-8b0edb00c6aa
groups:
  BinaryBeauty:
  - admin
  BinaryBench:
  - admin
servers:
  hub:
    motd: '&1BinaryNetwork Hub - Forced Host'
    address: localhost:25564
    restricted: false
  game:
    motd: '&1BinaryNetwork Game - Forced Host'
    address: localhost:25563
    restricted: false
  build:
    motd: '&1BinaryNetwork Build - Forced Host'
    address: localhost:25567
    restricted: false
timeout: 30000
player_limit: -1
listeners:
- query_port: 25566
  motd: '&1BinaryNetwork'
  priorities:
  - hub
  - game
  bind_local_address: true
  tab_list: SERVER
  query_enabled: false
  host: 0.0.0.0:25566
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 1
  tab_size: 60
  ping_passthrough: false
  force_default_server: true
permissions:
  default:
  - bungeecord.command.server
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
